query articles{
  articles {
    data {
      id
      attributes {
        title
        body
        date
        description
        slug
      }
    }
  }
}

query article($id: ID!) {
  article(id: $id) {
    data {
      id
      attributes {
        title
        body
        date
        description
        slug
      }
    }
  }
}